# Generated by Django 3.1.3 on 2020-12-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_softskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Опис')),
                ('company_name', models.CharField(max_length=30, verbose_name='Назва компанії')),
                ('start', models.DateField(verbose_name='Дата')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Дата завершення')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Опис')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.profession')),
            ],
        ),
    ]
